spring.application.name=demo
# H2 Database (temporary, no installation needed)
spring.datasource.url=jdbc:h2:file:./data/urlshortenerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (database ko browser mein dekhne ke liye)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080
